version: '3.8'

services:
  auth-server-blue:
    image: geooeg/jjubul-auth:1.1.45
    container_name: jjubul-auth-server-blue
    ports:
      - "9000:9000"
    environment:
      CORE_DB_URL: ${CORE_DB_URL}
      CORE_DB_USERNAME: ${CORE_DB_USERNAME}
      CORE_DB_PASSWORD: ${CORE_DB_PASSWORD}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - mysql-db
    networks:
      - jjubul-network
  
  mysql-db:
    image: mysql:8.0
    container_name: jjubul-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - jjubul-network

networks:
  jjubul-network:
    driver: bridge

volumes:
  mysql-volume:
